### ISSUE TITLE
Error Plugin Wordpress

### ISSUE THREAD

**Issue by MrChinnOh** [KirianCaumes/Eventus#2]
We have an error when activating the plugin.

<img width="760" alt="image" src="https://github.com/KirianCaumes/Eventus/assets/88510257/d80ab3af-dcd8-40cc-9b73-cae6933c1fe2">

**Comment by KirianCaumes** [comment]
Related to changes on the FFHB APIs, see my response in [your other issue](https://github.com/KirianCaumes/FFHB-Championship-Calendar-Generator/issues/2#issuecomment-1575729928).

I'll try to look at it in the coming days, but I don't use this plugin at all anymore, so it's not a priority.

I'm even suprised that someone is using it 😅

**Comment by KirianCaumes** [comment]
After further investigation, this problem is not related to the new FFHB API.

Eventus plugin is no longer working on PHP version > 8.x, because "[match](https://www.php.net/manual/fr/control-structures.match.php)" is now a keyword. So the class "Match" of Eventus generate a conflict.

The solution might be to rename each use of "Match" entity to "MatchEntity" or "Game" for example.

👉 But, I will not fix the project. I do longer use it and I haven't developed in PHP for a while.

On the other hand, I started to fix the FFHB Api with the new API, but some things are a bit too complicated to fixed quick (some API result are different, and data are separated in different API/pages). I won't go further now. You can still find the work started on [branch/feature_new_ffhb-api](https://github.com/KirianCaumes/Eventus/tree/feature_new_ffhb-api).

I will update the Readme.md to explain this.

Feel free to open a Pull Request if you really want to fix the problems.

Finally, if you use PHP < v8.x and Wordpress v?, the plugin still work with the old API (for how long?) and when the old API is going to be dead, you can still create manually the "match" and some features.
